sudo: false
dist: trusty
language: ruby
rvm:
 - 2.2
 - jruby
jobs:
  include:
    - script: echo "Running unit tests (1)"
    - script: echo "Running unit tests (2)"
    - stage: GitHub Release
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        api_key: ${{ secrets.GITHUB_TOKEN }}
        skip_cleanup: true
        on:
          tags: true
